# Generated by Django 4.2.5 on 2023-12-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('processos_aquisitivos', '0016_proaqdadosgerais_outro_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProaqItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('numero_item', models.IntegerField()),
                ('tipo_cota', models.CharField(choices=[('principal', 'Principal'), ('reservada', 'Reservada')], max_length=20)),
                ('cmm_estimado', models.FloatField()),
                ('qtd_a_ser_contratada', models.FloatField()),
                ('valor_unitario_estimado', models.FloatField()),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_item_deletado', to='usuarios.usuario')),
                ('proaq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_item', to='processos_aquisitivos.proaqdadosgerais')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_item_produto', to='produtos.produtosfarmaceuticos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_item_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_item_registro', to='usuarios.usuario')),
            ],
        ),
    ]
