# Generated by Django 4.2.5 on 2023-12-27 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0019_remove_proaqevolucao_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqevolucao',
            name='data_saida',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
