# Generated by Django 4.2.5 on 2024-01-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0020_alter_proaqevolucao_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='proaqtramitacao',
            name='etapa_processo_outro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proaqevolucao',
            name='fase',
            field=models.CharField(choices=[('', 'Não Informado'), ('fase1', 'Documentos Iniciais'), ('fase2', 'Tramitação Pré-Contratual'), ('fase3', 'Contratação'), ('fase4', 'Execução do Contrato'), ('fase5', 'Prestação de Contas'), ('fase6', 'Encerrado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proaqtramitacao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_tramitacao_setor', to='processos_aquisitivos.proaq_area_ms'),
        ),
    ]
