# Generated by Django 4.2.5 on 2024-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0021_proaqtramitacao_etapa_processo_outro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqtramitacao',
            name='etapa_processo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proaqtramitacao',
            name='etapa_processo_outro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
