# Generated by Django 4.2.5 on 2024-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0022_alter_proaqtramitacao_etapa_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqitens',
            name='tipo_cota',
            field=models.CharField(choices=[('', 'Não Informado'), ('principal', 'Principal'), ('reservada', 'Reservada'), ('exclusiva', 'Exclusiva'), ('nao_se_aplica', 'Não Se Aplica')], max_length=20),
        ),
    ]
