# Generated by Django 4.2.5 on 2024-01-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('sobre_sisdaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPontoControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('data', models.DateField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('pauta', models.TextField(blank=True, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('encaminhamentos', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ponto_controle_deletado', to='usuarios.usuario')),
                ('responsavel_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ponto_controle_responsavel', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ponto_controle_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ponto_controle_registro', to='usuarios.usuario')),
            ],
        ),
    ]
