# Generated by Django 4.2.5 on 2024-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_sisdaf', '0002_registropontocontrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropontocontrole',
            name='participantes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
