# Generated by Django 4.2.5 on 2024-01-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_sisdaf', '0003_registropontocontrole_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropontocontrole',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropontocontrole',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropontocontrole',
            name='tipo_reuniao',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], max_length=20, null=True),
        ),
    ]
