# Generated by Django 4.2.5 on 2024-01-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_sisdaf', '0004_registropontocontrole_horario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropontocontrole',
            old_name='horario',
            new_name='horario_fim',
        ),
        migrations.AddField(
            model_name='registropontocontrole',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
