# Generated by Django 4.2.5 on 2024-01-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('sobre_sisdaf', '0005_rename_horario_registropontocontrole_horario_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('nao_iniciado', 'Não Iniciado'), ('em_desenvolvimento', 'Em desenvolvimento'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('tipo_item', models.CharField(blank=True, choices=[('corretivo', 'Corretivo'), ('adaptativo', 'Adaptativo'), ('evolutivo', 'Evolutivo')], max_length=20, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='backlog_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='backlog_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='backlog_registro', to='usuarios.usuario')),
            ],
        ),
    ]
