# Generated by Django 4.2.5 on 2024-01-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('sobre_sisdaf', '0006_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='responsavel_realizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='backlog_responsavel', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
