# Generated by Django 4.2.5 on 2024-01-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('gestao_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('cns', models.CharField(max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('data_obito', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=20)),
                ('cor_pele', models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=20)),
                ('orientacao_sexual', models.CharField(choices=[('heterossexual', 'Heterossexual'), ('homossexual', 'Homossexual'), ('bissexual', 'Bissexual'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=20)),
                ('naturalidade_cod_ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispensacao_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispensacao_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispensacao_registro', to='usuarios.usuario')),
            ],
        ),
    ]
