# Generated by Django 4.2.5 on 2024-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_pacientes', '0002_dispensacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensacoes',
            name='cns',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='cor_pele',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='data_obito',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='naturalidade_cod_ibge',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='orientacao_sexual',
        ),
        migrations.RemoveField(
            model_name='dispensacoes',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cns',
            field=models.CharField(max_length=18),
        ),
    ]
