# Generated by Django 4.2.5 on 2024-01-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('gestao_pacientes', '0005_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensacoes',
            name='ciclo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='cid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='comprovante_doc_sei',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='data_consumo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='fase_tratamento',
            field=models.CharField(blank=True, choices=[('ataque', 'Ataque'), ('inicial', 'Inicial'), ('manutencao', 'Manutenção'), ('nao_se_aplica', 'Não se aplica'), ('', 'Não Informado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='local_aplicacao_cod_ibge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='local_aplicacao_unidade_saude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='numero_pedido_sismat',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='numero_processo_sei',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='origem_demanda_judicial',
            field=models.CharField(blank=True, choices=[('cgceaf', 'CGCEAF'), ('djud', 'DJUD'), ('', 'Não Informado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispensacao_paciente', to='gestao_pacientes.pacientes'),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispensacao_produto', to='produtos.produtosfarmaceuticos'),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em Análise'), ('enviado', 'Enviado'), ('consumido', 'Consumido'), ('cancelado', 'Cancelado'), ('', 'Não Informado')], default='nao_informado', max_length=20),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='uf_solicitacao',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispensacoes',
            name='via_atendimento',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('judicial', 'Judicial'), ('', 'Não Informado')], default='administrativa', max_length=20),
        ),
    ]
