# Generated by Django 4.2.5 on 2024-01-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_pacientes', '0007_alter_dispensacoes_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensacoes',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
