# Generated by Django 4.2.5 on 2024-02-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('gestao_pacientes', '0009_alter_dispensacoes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensacoes',
            name='uf_solicitacao',
            field=models.CharField(blank=True, choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO'), ('NI', 'Não Informado')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Atendimento_Judicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('data_solicitacao', models.DateTimeField()),
                ('origem_solicitacao', models.CharField(choices=[('cgceaf', 'CGCEAF'), ('djud', 'DJUD'), ('', 'Não Informado')], max_length=10)),
                ('meio_solicitacao', models.CharField(choices=[('email', 'E-mail'), ('oficio', 'Ofício'), ('processo_sei', 'Processo Sei')], max_length=15)),
                ('uf_origem', models.CharField(choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO'), ('NI', 'Não Informado')], max_length=2)),
                ('acao_civil_publica', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10)),
                ('documento_sei_comprovante', models.CharField(max_length=10)),
                ('processo_sei_comprovante', models.CharField(max_length=20)),
                ('total_produtos', models.FloatField()),
                ('total_pacientes', models.IntegerField(blank=True, null=True)),
                ('unidade_daf', models.CharField(choices=[('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE'), ('', 'Não Informado')], max_length=10)),
                ('analise_tecnica', models.CharField(choices=[('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('nao_analisado', 'Não analisado')], max_length=100)),
                ('motivo_recusa', models.TextField(blank=True, default='Não informado.', null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('tipo_disponibilizacao', models.CharField(choices=[('remanejamento', 'Remanejamento'), ('transferencia', 'Transferência')], max_length=100)),
                ('data_disponibilizacao', models.DateTimeField(blank=True, null=True)),
                ('total_disponibilizado', models.FloatField()),
                ('numero_pedido', models.CharField(blank=True, max_length=10, null=True)),
                ('total_pedido', models.FloatField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3)),
                ('motivo_cancelamento', models.TextField(blank=True, default='Não informado.', null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentojudicial_deletado', to='usuarios.usuario')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentojudicial_produto', to='produtos.produtosfarmaceuticos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentojudicial_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentojudicial_registro', to='usuarios.usuario')),
            ],
        ),
    ]
