# Generated by Django 4.2.5 on 2024-02-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('nome', models.CharField(blank=True, max_length=140, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('daf_cgceaf', models.BooleanField(default=False)),
                ('daf_cgafb', models.BooleanField(default=False)),
                ('daf_cgafme', models.BooleanField(default=False)),
                ('daf_farmacia_popular', models.BooleanField(default=False)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_kit_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_kit', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_rkit', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='KitsProdutosFarmaceuticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_kits_produtos_deletado', to='usuarios.usuario')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_kit', to='produtos.kits')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kit_produto', to='produtos.produtosfarmaceuticos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_kits_produtos', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_kits_produtos', to='usuarios.usuario')),
            ],
        ),
    ]
