# Generated by Django 4.2.5 on 2024-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_kits_kitsprodutosfarmaceuticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitsprodutosfarmaceuticos',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
