# Generated by Django 4.2.4 on 2023-09-04 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('dp_cpf', models.CharField(max_length=14, unique=True)),
                ('dp_nome_completo', models.CharField(max_length=100)),
                ('dp_data_nascimento', models.DateField(blank=True, null=True)),
                ('dp_genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=15, null=True)),
                ('dp_cor_pele', models.CharField(blank=True, choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=15, null=True)),
                ('foto_usuario', models.ImageField(blank=True, upload_to='fotos_usuarios/%Y/%m/%d/')),
                ('ctt_ramal_ms', models.CharField(blank=True, max_length=4, null=True)),
                ('ctt_celular', models.CharField(blank=True, max_length=17, null=True)),
                ('ctt_email_ms', models.EmailField(blank=True, max_length=40, null=True)),
                ('ctt_email_pessoal', models.EmailField(blank=True, max_length=40, null=True)),
                ('rs_linkedin', models.URLField(blank=True, max_length=150, null=True)),
                ('rs_lattes', models.URLField(blank=True, max_length=150, null=True)),
                ('vms_vinculo', models.CharField(blank=True, choices=[('consultor', 'Consultor Técnico'), ('servidor_federal', 'Servidor Federal'), ('servidor_estadual', 'Servidor Estadual'), ('servidor_municipal', 'Servidor Municipal'), ('nao_informado', 'Não Informado')], max_length=20, null=True)),
                ('vms_orgao', models.CharField(blank=True, choices=[('min_saude', 'Ministério da Saúde'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=120, null=True)),
                ('vms_orgao_outro', models.CharField(blank=True, max_length=120, null=True)),
                ('aloc_unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('aloc_setor', models.CharField(blank=True, max_length=60, null=True)),
                ('aloc_data_inicio', models.DateField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_relacionado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
