# Generated by Django 4.2.5 on 2023-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0037_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('epp', 'EPP'), ('demais', 'Demais'), ('me', 'ME'), ('grande_empresa', 'Grande Empresa')], max_length=20),
        ),
    ]
