# Generated by Django 4.2.5 on 2023-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0041_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('demais', 'Demais'), ('me', 'ME'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa')], max_length=20),
        ),
    ]
