# Generated by Django 4.2.5 on 2023-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0042_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('medio_porte', 'Médio Porte'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('me', 'ME'), ('mei', 'MEI')], max_length=20),
        ),
    ]
