# Generated by Django 4.2.5 on 2023-12-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0047_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('epp', 'EPP'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('me', 'ME'), ('mei', 'MEI')], max_length=20),
        ),
    ]
