# Generated by Django 4.2.5 on 2023-12-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0051_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('me', 'ME'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('medio_porte', 'Médio Porte'), ('epp', 'EPP'), ('mei', 'MEI')], max_length=20),
        ),
    ]
