# Generated by Django 4.2.5 on 2023-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0055_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('me', 'ME'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('demais', 'Demais')], max_length=20),
        ),
    ]
