# Generated by Django 4.2.5 on 2024-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0067_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('epp', 'EPP'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('me', 'ME')], max_length=20),
        ),
    ]
