# Generated by Django 4.2.5 on 2024-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0069_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('me', 'ME'), ('demais', 'Demais')], max_length=20),
        ),
    ]
