# Generated by Django 4.2.5 on 2024-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0071_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('mei', 'MEI'), ('demais', 'Demais'), ('me', 'ME'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
