# Generated by Django 4.2.5 on 2024-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0074_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('demais', 'Demais'), ('medio_porte', 'Médio Porte'), ('me', 'ME'), ('grande_empresa', 'Grande Empresa'), ('mei', 'MEI')], max_length=20),
        ),
    ]
