# Generated by Django 4.2.5 on 2024-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0076_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte'), ('epp', 'EPP'), ('mei', 'MEI'), ('me', 'ME')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('público', 'Público'), ('privado', 'Privado')], default='privado', max_length=10),
        ),
    ]
