# Generated by Django 4.2.5 on 2024-01-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0080_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('epp', 'EPP'), ('mei', 'MEI'), ('me', 'ME')], max_length=20),
        ),
    ]
