# Generated by Django 4.2.5 on 2024-01-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0083_alter_fornecedores_hierarquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('me', 'ME'), ('medio_porte', 'Médio Porte'), ('grande_empresa', 'Grande Empresa'), ('epp', 'EPP'), ('mei', 'MEI'), ('demais', 'Demais')], max_length=20),
        ),
    ]
