# Generated by Django 4.2.5 on 2024-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0085_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('me', 'ME'), ('mei', 'MEI'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
