# Generated by Django 4.2.5 on 2024-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0089_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='telefone1',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='telefone2',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('me', 'ME'), ('demais', 'Demais'), ('medio_porte', 'Médio Porte'), ('grande_empresa', 'Grande Empresa'), ('mei', 'MEI')], max_length=20),
        ),
    ]
