# Generated by Django 4.2.5 on 2024-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0090_fornecedores_email_fornecedores_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('me', 'ME'), ('mei', 'MEI'), ('epp', 'EPP')], max_length=20),
        ),
    ]
