# Generated by Django 4.2.5 on 2023-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customlog_model_customlog_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('unidade_daf', models.CharField(choices=[('', 'Não Informado'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=50)),
                ('mensagem', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('data_desativacao', models.DateTimeField()),
            ],
        ),
    ]
