# Generated by Django 4.2.5 on 2024-02-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('main', '0007_alertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=120)),
                ('imagem_card', models.CharField(choices=[('arquivo', 'Arquivo'), ('atencao', 'Atenção'), ('atualizacao', 'Atualização'), ('bloqueio', 'Bloqueio'), ('calendario', 'Calendário'), ('chat', 'Chat'), ('check', 'Check'), ('configuracao', 'Configuração'), ('coracao', 'Coração'), ('curtir', 'Curtir'), ('descurtir', 'Descurtir'), ('documento', 'Documento'), ('ferramenta', 'Ferramenta'), ('ideia', 'Ideia'), ('lupa', 'Lupa'), ('mais', 'Mais'), ('mensagem', 'Mensagem'), ('microfone', 'Microfone'), ('mundo', 'Mundo'), ('pacote', 'Pacote'), ('play', 'Play'), ('questao', 'Questão'), ('relogio', 'Relógio')], max_length=80)),
                ('resumo', models.TextField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('', 'Não Informado')], max_length=10)),
                ('alcance', models.CharField(choices=[('', 'Não Informado'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE'), ('daf', 'DAF')], max_length=10)),
                ('link_mais_informacoes', models.TextField(blank=True, default='Não possui.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='informe_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informe_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informe_registro', to='usuarios.usuario')),
            ],
        ),
    ]
