# Generated by Django 4.2.5 on 2023-12-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contratosobjetos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratosobjetos',
            name='qtd_contratada',
        ),
    ]
