# Generated by Django 4.2.5 on 2023-12-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('contratos', '0009_remove_contratosobjetos_qtd_contratada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosParcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('numero_parcela', models.IntegerField()),
                ('qtd_contratada', models.IntegerField()),
                ('data_previsao_entrega', models.DateField()),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_parcela_deletado', to='usuarios.usuario')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parcela_objeto', to='contratos.contratosobjetos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_parcela_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_parcela_registro', to='usuarios.usuario')),
            ],
        ),
    ]
