# Generated by Django 4.2.5 on 2023-12-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contratosparcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosparcelas',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parcela_contrato', to='contratos.contratos'),
            preserve_default=False,
        ),
    ]
