# Generated by Django 4.2.5 on 2023-12-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_contratosparcelas_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosobjetos',
            name='arp_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_objeto', to='contratos.contratosarpsitens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratosparcelas',
            name='observacoes_gerais',
            field=models.TextField(blank=True, default='Sem observações.', null=True),
        ),
    ]
