# Generated by Django 4.2.5 on 2023-12-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('contratos', '0012_contratosobjetos_arp_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosEntregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('numero_entrega', models.IntegerField()),
                ('qtd_entregue', models.IntegerField()),
                ('data_entrega', models.DateField()),
                ('local_entrega', models.CharField(choices=[('', ''), ('apenas_almoxarifado', 'Almoxarifado'), ('apenas_ses', 'SES'), ('apenas_almoxarifado_ses', 'Almoxarifado e SES')], max_length=30)),
                ('notas_recebidas', models.CharField(choices=[('nao_informado', 'Não Informado'), ('nenhuma', 'Nenhuma'), ('parcial', 'Parcial'), ('todas', 'Todas')], max_length=20)),
                ('notas_status', models.CharField(choices=[('nao_informado', 'Não Informado'), ('nao_validadas', 'Não Validadas'), ('validadas', 'Validadas')], max_length=20)),
                ('notas_pagamentos', models.CharField(choices=[('nao_informado', 'Não Informado'), ('nao_realizado', 'Não Realizado'), ('realizado', 'Realizado')], max_length=20)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_entrega_deletado', to='usuarios.usuario')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrega_objeto', to='contratos.contratosobjetos')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrega_parcela', to='contratos.contratosparcelas')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_entrega_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_entrega_registro', to='usuarios.usuario')),
            ],
        ),
    ]
