# Generated by Django 4.2.5 on 2023-12-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_contratosentregas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratosentregas',
            name='objeto',
        ),
        migrations.AddField(
            model_name='contratosentregas',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrega_contrato', to='contratos.contratos'),
        ),
    ]
