# Generated by Django 4.2.5 on 2023-12-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('contratos', '0014_remove_contratosentregas_objeto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosFiscais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('fiscal_outro', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.CharField(choices=[('', ''), ('apenas_almoxarifado', 'Almoxarifado'), ('apenas_ses', 'SES'), ('apenas_almoxarifado_ses', 'Almoxarifado e SES')], max_length=30)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_contrato', to='contratos.contratos')),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_contrato_deletado', to='usuarios.usuario')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_contrato_usuario', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_contrato_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiscal_contrato_registro', to='usuarios.usuario')),
            ],
        ),
    ]
