# Generated by Django 4.2.5 on 2023-12-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_contratosfiscais'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosfiscais',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
            preserve_default=False,
        ),
    ]
