# Generated by Django 4.2.5 on 2023-12-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('contratos', '0019_alter_contratosfiscais_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('numero_empenho', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('nao_informado', 'Nâo Informado'), ('pre_empenho', 'Pré-Empenho'), ('empenhado', 'Empenhado'), ('cancelado', 'Cancelado')], max_length=15)),
                ('data_solicitacao', models.DateField()),
                ('data_empenho', models.DateField(blank=True, null=True)),
                ('responsavel_empenho_outro', models.CharField(max_length=100)),
                ('processo_sei', models.CharField(max_length=20)),
                ('documento_sei', models.CharField(max_length=15)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_usuario_delete', to='usuarios.usuario')),
                ('responsavel_empenho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_usuario_responsavel', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_usuario_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_usuario_registro', to='usuarios.usuario')),
            ],
        ),
    ]
