# Generated by Django 4.2.5 on 2023-12-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_empenhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhos',
            name='unidade_daf',
            field=models.CharField(choices=[('', 'Não Informado'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], default='cgceaf', max_length=15),
            preserve_default=False,
        ),
    ]
