# Generated by Django 4.2.5 on 2023-12-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_empenhos_unidade_daf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenhos',
            name='responsavel_empenho',
        ),
        migrations.RemoveField(
            model_name='empenhos',
            name='responsavel_empenho_outro',
        ),
    ]
