# Generated by Django 4.2.5 on 2023-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_remove_empenhos_responsavel_empenho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenhos',
            name='status',
            field=models.CharField(choices=[('', 'Nâo Informado'), ('pre_empenho', 'Pré-Empenho'), ('empenhado', 'Empenhado'), ('cancelado', 'Cancelado')], max_length=15),
        ),
    ]
