# Generated by Django 4.2.5 on 2023-12-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
        ('contratos', '0023_alter_empenhos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpenhosItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('valor_empenhado', models.FloatField()),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_item_usuario_delete', to='usuarios.usuario')),
                ('empenho', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_item', to='contratos.empenhos')),
                ('parcela', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_parcela', to='contratos.contratosparcelas')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_item_usuario_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empenho_item_usuario_registro', to='usuarios.usuario')),
            ],
        ),
    ]
