# Generated by Django 4.2.5 on 2023-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_empenhositens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosarpsitens',
            name='tipo_cota',
            field=models.CharField(choices=[('', 'Não Informado'), ('principal', 'Principal'), ('reservada', 'Reservada'), ('nao_se_aplica', 'Não Se Aplica')], max_length=20),
        ),
    ]
