# Generated by Django 4.2.5 on 2024-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_alter_contratosarpsitens_tipo_cota'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosparcelas',
            name='qtd_doada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
