# Generated by Django 4.2.5 on 2024-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_contratosparcelas_qtd_doada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosparcelas',
            name='qtd_doada',
            field=models.IntegerField(default=0),
        ),
    ]
