# Generated by Django 4.2.5 on 2024-01-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_alter_contratosparcelas_qtd_doada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenhositens',
            name='qtd_empenhado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
