# Generated by Django 4.2.5 on 2024-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_empenhositens_qtd_empenhado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosfiscais',
            name='documento_sei',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratosarpsitens',
            name='tipo_cota',
            field=models.CharField(choices=[('', 'Não Informado'), ('principal', 'Principal'), ('reservada', 'Reservada'), ('exclusiva', 'Exclusiva'), ('nao_se_aplica', 'Não Se Aplica')], max_length=20),
        ),
    ]
