# Generated by Django 4.2.5 on 2024-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_contratosfiscais_documento_sei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(choices=[('', 'Não Informado'), ('ordinario', 'Ordinário'), ('nota_empenho', 'Nota de Empenho')], default='nao_informado', max_length=20),
        ),
    ]
