# Generated by Django 4.2.5 on 2024-01-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_contratos_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(choices=[('', 'Não Informado'), ('ordinario', 'Ordinário'), ('nota_empenho', 'Nota de Empenho')], default='ordinario', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratosobjetos',
            name='arp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_objeto', to='contratos.contratosarpsitens'),
        ),
    ]
